apiVersion: apps/v1 #tells kubernetes about the poll of objects that we want to draw from
kind: Deployment #this is the type of object that we want to create from that poll
metadata: #Config options
  name: expiration-redis-depl #when deployment is created give it name auth-depl
spec: # specify how the deployment is going to behave
  replicas: 1
  selector: 
    matchLabels: #the deployment manages all the pods that are having label app auth
      app: expiration-redis
  template: #exact configuration of the pods that we want the deployment to create
    metadata:
      labels:
        app: expiration-redis
    spec:
      containers:
        - name: expiration-redis
          image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv
spec:
  selector:
    app: expiration-redis
  ports:
    - name: expiration-redis
      protocol: TCP
      port: 6379
      targetPort: 6379