apiVersion: apps/v1 #tells kubernetes about the poll of objects that we want to draw from
kind: Deployment #this is the type of object that we want to create from that poll
metadata: #Config options
  name: orders-depl #when deployment is created give it name auth-depl
spec: # specify how the deployment is going to behave
  replicas: 1
  selector: 
    matchLabels: #the deployment manages all the pods that are having label app auth
      app: orders
  template: #exact configuration of the pods that we want the deployment to create
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: sachetwasti61/orders
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000